version: '3.8'

services:
  streamlit-app:
    build: .
    container_name: exchangetrack-app
    ports:
      - "8501:8501"
    restart: unless-stopped
    networks:
      - exchangetrack_network

  pipeline:
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    container_name: exchangetrack-pipeline
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Istanbul
    restart: unless-stopped
    networks:
      - exchangetrack_network

networks:
  exchangetrack_network:
    driver: bridge